language: go
go:
  - master

addons:
  apt:
    packages:
      - python-pygments

install:
  - rm -rf public || exit 0
  - go get github.com/gohugoio/hugo

script:
  - hugo

deploy:
  local_dir: public
  provider: pages
  skip_cleanup: true
  keep-history: true
  target_branch: master
  github_token: $GITHUB_TOKEN
  on:
    branch: master
