baseURL: https://eiparyen.github.io
languageCode: en-us
title: Eiparyen
subtitle: ai-PAIR-ee-in
theme: beautifulhugo
metaDataFormat: yaml
pygmentsStyle: trac
pygmentsUseClasses: true
pygmentsCodeFences: true
pygmentsCodefencesGuessSyntax: true
disqusShortname: eiparyen

Params:
  comments: true
  delayDisqus: true
  useHLJS: true
  socialShare: true
  rss: true

blackfriday:
  plainIDAnchors: true
  hrefTargetBlank: true

menu:
  main:
    - name: About
      url: about/
      weight: 1
    - name: pwnable
      url: pwnable/
      weight: 2
